FROM 6789012345/myjdk-alpine:latest
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app/
RUN pwd
RUN ls -la
RUN chmod 755 /usr/src/app/
RUN javac Calculator.java -d /usr/src/app/
CMD ["java", "-cp", "/usr/src/app/maven", "Calculator"]