FROM 6789012345/harsha_test:v1
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app/
RUN chmod 755 /usr/src/app/
RUN javac Test1.java -d /usr/src/app/
CMD ["java", "-cp", "/usr/src/app/", "Test1"]